# Generated by Django 4.2.16 on 2024-10-19 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_category_wishlist_transaction_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('sold', 'Sold')], default='available', max_length=10),
        ),
    ]
