# Generated by Django 4.2.16 on 2024-11-03 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_description_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='transaction',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.transaction'),
            preserve_default=False,
        ),
    ]
